In [1]:
import theano.tensor as T
import theano
import numpy as np
import matplotlib.pyplot as plt
theano.config.compute_test_value = "ignore"



In [2]:
np.array([2,4,5])

array([2, 4, 5])

In [3]:
Zx = T.matrix("Zx")
PV = T.vector("PV")
form = T.vector()
#b = T.vector()

PV2 = T.concatenate((T.stack(-9999), PV, T.stack(9999)))

def clap(a, b, form, Zx):
    return T.ge(Zx,a)*T.le(Zx,b)*form

components, updates = theano.scan(fn = clap,
                                 outputs_info = None,
                                 sequences = [dict(input=  PV2, taps = [0,1]), form],
                                 non_sequences = Zx)

f = theano.function([Zx, PV, form], components, on_unused_input='ignore',allow_input_downcast=True)

In [4]:
 a  =f(np.random.uniform(0,10, (10,10)),(5,2), [7,8,])

In [5]:
a

array([[[ 7.,  0.,  0.,  7.,  7.,  7.,  7.,  0.,  0.,  7.],
        [ 7.,  7.,  7.,  0.,  0.,  7.,  0.,  0.,  7.,  0.],
        [ 0.,  7.,  0.,  7.,  0.,  0.,  0.,  7.,  0.,  0.],
        [ 7.,  0.,  7.,  0.,  0.,  0.,  7.,  0.,  7.,  0.],
        [ 7.,  7.,  0.,  0.,  7.,  7.,  7.,  0.,  7.,  7.],
        [ 7.,  0.,  0.,  7.,  7.,  7.,  0.,  0.,  7.,  0.],
        [ 0.,  7.,  0.,  0.,  0.,  0.,  7.,  7.,  7.,  7.],
        [ 0.,  7.,  0.,  7.,  7.,  7.,  7.,  0.,  0.,  0.],
        [ 0.,  7.,  7.,  7.,  7.,  0.,  0.,  7.,  7.,  7.],
        [ 7.,  0.,  0.,  7.,  7.,  7.,  7.,  7.,  0.,  7.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,

In [6]:
a

array([[[ 7.,  0.,  0.,  7.,  7.,  7.,  7.,  0.,  0.,  7.],
        [ 7.,  7.,  7.,  0.,  0.,  7.,  0.,  0.,  7.,  0.],
        [ 0.,  7.,  0.,  7.,  0.,  0.,  0.,  7.,  0.,  0.],
        [ 7.,  0.,  7.,  0.,  0.,  0.,  7.,  0.,  7.,  0.],
        [ 7.,  7.,  0.,  0.,  7.,  7.,  7.,  0.,  7.,  7.],
        [ 7.,  0.,  0.,  7.,  7.,  7.,  0.,  0.,  7.,  0.],
        [ 0.,  7.,  0.,  0.,  0.,  0.,  7.,  7.,  7.,  7.],
        [ 0.,  7.,  0.,  7.,  7.,  7.,  7.,  0.,  0.,  0.],
        [ 0.,  7.,  7.,  7.,  7.,  0.,  0.,  7.,  7.,  7.],
        [ 7.,  0.,  0.,  7.,  7.,  7.,  7.,  7.,  0.,  7.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,

In [9]:
type(np.float32(np.inf))

numpy.float32

In [37]:
a = T.scalar()

a.eval({a:1e50})

array(inf, dtype=float32)

In [14]:
help(theano.scan)

Help on function scan in module theano.scan_module.scan:

scan(fn, sequences=None, outputs_info=None, non_sequences=None, n_steps=None, truncate_gradient=-1, go_backwards=False, mode=None, name=None, profile=False, allow_gc=None, strict=False)
    This function constructs and applies a Scan op to the provided
    arguments.
    
    Parameters
    ----------
    fn
        ``fn`` is a function that describes the operations involved in one
        step of ``scan``. ``fn`` should construct variables describing the
        output of one iteration step. It should expect as input theano
        variables representing all the slices of the input sequences
        and previous values of the outputs, as well as all other arguments
        given to scan as ``non_sequences``. The order in which scan passes
        these variables to ``fn``  is the following :
    
        * all time slices of the first sequence
        * all time slices of the second sequence
        * ...
        * all time sli

In [11]:
count=0
for i in range(1,11):
    count+=1
print( count)

def caca(previous_count):
    return previous_count+1

import theano as th
i = T.iscalar('i')
results, updates = th.scan(fn= caca,
                            outputs_info=0,
                            n_steps=i)

10
